name: Stock Cron

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          curl \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            https://stock-app-two-kappa.vercel.app/pushMsg_830
